apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'application'
apply plugin: 'distribution'

targetCompatibility = 5;
sourceCompatibility = 5;

mainClassName = 'org.betacraft.launcher.Launcher'

repositories {
	mavenCentral()
	maven {
		url = uri("https://repo.blueberrymc.net/repository/maven-releases/")
	}
}

jar {
	from {
		configurations.runtime.collect {
			it.isDirectory() ? it : zipTree(it)
		}
	}
	manifest {
		attributes(
			'Main-Class': 'org.betacraft.launcher.Launcher'
		)
	}
}

startScripts {
    doLast {
        def windowsScriptFile = file getWindowsScript()
        def unixScriptFile = file getUnixScript()
        windowsScriptFile.text = windowsScriptFile.text.replace('set APP_HOME=%DIRNAME%..', 'set APP_HOME=%DIRNAME%')
        unixScriptFile.text = unixScriptFile.text.replace('cd "`dirname \"$PRG\"`/.." >/dev/null', 'cd "`dirname \"$PRG\"`" >/dev/null')
    }
}

distributions {
	macOS {
		baseName = 'BetaCraft Launcher.app'
		contents {
			into('Contents') {
				from { 'src/dist/MacOS/meta' }
			}
			into('Contents/Resources') {
				from { 'src/dist/MacOS/Resources' }
			}
			into ('Contents/MacOS/lib') {	
				from { configurations.compileClasspath }
				from { jar }
			}
			into ( 'Contents/MacOS' ) {
				from ( 'src/dist/MacOS/Scripts' ){
					fileMode(493) //This is the decimal representation of the octal '755' permission set
				}
			}
			into ('Contents/MacOS/lib/security') {
				from { 'src/security' }
			}
		}
	}
	windows{
		baseName = 'BetaCraft Launcher (Windows)'
		contents {
			from(startScripts){
				include '*.bat'
			}
			into('lib'){
				from { configurations.compileClasspath }
				from { jar }
			}
		}
	}
	linux{
			baseName = 'BetaCraft Launcher (Linux)'
		contents {
			from(startScripts){
				exclude '*.bat'
				fileMode(493)
			}
			into('lib'){
				from { configurations.compileClasspath }
				from { jar }
			}
		}
	}
}

dependencies {
	runtime 'com.google.code.gson:gson:2.4'
	implementation 'org.bouncycastle:bcprov-jdk15to18:1.82'
	implementation 'org.bouncycastle:bctls-jdk15to18:1.82'
	implementation 'org.bouncycastle:bcpkix-jdk15to18:1.82'
	implementation 'org.bouncycastle:bcutil-jdk15to18:1.82'
	implementation 'commons-httpclient:commons-httpclient:3.1'
	compileOnly 'com.google.code.gson:gson:2.4'
}
